[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9

lib_deps =
  lovyan03/LovyanGFX @ ^1.2.7

build_flags =
  -DCORE_DEBUG_LEVEL=0
